services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 9999:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: always
    user: root
    networks:
          - jenkins-network

networks:
  jenkins-network:
